name: my-workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: My 1st step
        run: echo "My 1st step"

      - name: My 2nd step
        run: echo "My 2nd step"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: My 3rd step
        run: echo "My 3rd step"

      - name: My 4th step
        run: echo "My 4th step"
